/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'us-east-2',
	aws_cognito_identity_pool_id:
		'us-east-2:d8733e3f-4abf-48da-b58d-912c20219030',
	aws_cognito_region: 'us-east-2',
	aws_user_pools_id: 'us-east-2_WkvHebcvT',
	aws_user_pools_web_client_id: '7rgu23nu36ah1e5icednhg58gu',
	oauth: {},
	aws_cognito_username_attributes: [],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: ['EMAIL'],
	aws_cognito_mfa_configuration: 'OFF',
	aws_cognito_mfa_types: ['SMS'],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: []
	},
	aws_cognito_verification_mechanisms: ['EMAIL'],
	aws_user_files_s3_bucket: 'expouploads22309-dev',
	aws_user_files_s3_bucket_region: 'us-east-2'
}

export default awsmobile
